INSERT INTO COMPANY (NAME, TAX_ID, ADDRESS, CITY, PROVINCE, POSTAL_CODE)
SELECT 'Frutas del Norte S.L.', 'B12345678', 'Calle Mayor 15', 'Oviedo', 'Asturias', 33001
    WHERE NOT EXISTS (SELECT 1 FROM COMPANY WHERE TAX_ID = 'B12345678');

INSERT INTO COMPANY (NAME, TAX_ID, ADDRESS, CITY, PROVINCE, POSTAL_CODE)
SELECT 'Construcciones Martínez S.A.', 'A87654321', 'Avda. de la Industria 42', 'Bilbao', 'Bizkaia', 48015
    WHERE NOT EXISTS (SELECT 1 FROM COMPANY WHERE TAX_ID = 'A87654321');

INSERT INTO COMPANY (NAME, TAX_ID, ADDRESS, CITY, PROVINCE, POSTAL_CODE)
SELECT 'Tecnología Verde SL', 'B11223344', 'Calle Innovación 3', 'Valencia', 'Valencia', 46022
    WHERE NOT EXISTS (SELECT 1 FROM COMPANY WHERE TAX_ID = 'B11223344');

INSERT INTO COMPANY (NAME, TAX_ID, ADDRESS, CITY, PROVINCE, POSTAL_CODE)
SELECT 'Panadería El Molino', 'J55667788', 'Camino de los Panaderos 12', 'Granada', 'Granada', 18008
    WHERE NOT EXISTS (SELECT 1 FROM COMPANY WHERE TAX_ID = 'J55667788');

INSERT INTO COMPANY (NAME, TAX_ID, ADDRESS, CITY, PROVINCE, POSTAL_CODE)
SELECT 'Consultoría Digital 360', 'C99887766', 'Plaza de España 7', 'Madrid', 'Madrid', 28008
    WHERE NOT EXISTS (SELECT 1 FROM COMPANY WHERE TAX_ID = 'C99887766');

INSERT INTO COMPANY (NAME, TAX_ID, ADDRESS, CITY, PROVINCE, POSTAL_CODE)
SELECT 'Logística y Transporte López', 'Z22334455', 'Polígono Sur Parcela 8', 'Sevilla', 'Sevilla', 41013
    WHERE NOT EXISTS (SELECT 1 FROM COMPANY WHERE TAX_ID = 'Z22334455');

INSERT INTO COMPANY (NAME, TAX_ID, ADDRESS, CITY, PROVINCE, POSTAL_CODE)
SELECT 'Moda Urbana S.L.', 'M44556677', 'Calle Comercio 10', 'Barcelona', 'Barcelona', 08001
    WHERE NOT EXISTS (SELECT 1 FROM COMPANY WHERE TAX_ID = 'M44556677');

INSERT INTO COMPANY (NAME, TAX_ID, ADDRESS, CITY, PROVINCE, POSTAL_CODE)
SELECT 'Energías Renovables Iberia', 'N33445566', 'Calle Sol 99', 'Zaragoza', 'Zaragoza', 50018
    WHERE NOT EXISTS (SELECT 1 FROM COMPANY WHERE TAX_ID = 'N33445566');
