CREATE TABLE COMPANY
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME        VARCHAR (255) NOT NULL,
    TAX_ID      VARCHAR (20) NOT NULL UNIQUE,
    ADDRESS     VARCHAR(255) NOT NULL,
    CITY        VARCHAR(100) NOT NULL,
    PROVINCE    VARCHAR(100) NOT NULL,
    POSTAL_CODE INTEGER NOT NULL
);
